version: 1.0
provider:
  name: openfaas
  gateway: https://gateway.ofc.do.controlplane.info
functions:
  satellite:
    lang: node10-express
    handler: ./server/app.js
    image: registry.digitalocean.com/do-good-images/satellite:latest

